
#pod init    初始化
#pod install 安装

inhibit_all_warnings!
platform:'ios','9.0'
target 'HuaHong' do
    
pod 'Aspects', '~> 1.4.1'
pod 'Masonry'
#已被依赖，无需重复导入
pod 'AFNetworking'
#pod 'SBJson4'
pod 'SVProgressHUD'
pod 'BaiduMapKit'
pod 'SSZipArchive'
pod 'SSKeychain', '~> 1.4.1'
pod 'SDWebImage', '~> 4.2.3'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'iCarousel', '~> 1.8.3'
pod 'AVOSCloud'
pod 'FaceppSDK', '~> 2.0.0'
pod 'SystemServices', '~> 2.0.1'
pod 'MLeaksFinder'
pod 'FMDB'
pod 'KVOController'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'MJExtension', '~> 3.0.15.1'
pod 'UICountingLabel', '~> 1.4.1'
pod 'NSDictionary-NilSafe'
pod 'SDCycleScrollView', '~> 1.73'
pod 'DZNEmptyDataSet'
pod 'TTGTagCollectionView'
pod 'MZTimerLabel', '~> 0.5.4'
pod 'MMDrawerController', '~> 0.6.0'
pod 'GPUImage'
pod 'Bugly'
pod 'BlocksKit'
pod 'XYPieChart'
#pod 'PNChart'
pod 'MJRefresh'
pod 'Shimmer'
pod 'pop'

pod 'YYCategories'
pod 'YYImage'
pod 'YYCache'
pod 'YYModel'
pod 'YYWebImage'
pod 'YYText'
pod 'YYKeyboardManager'
pod 'YYDispatchQueuePool'
pod 'YYAsyncLayer'
#pod 'YYKit'

#pod 'RATreeView', '~> 2.1.2'
#pod 'UITextView+Placeholder', '~> 1.2.0'
#pod 'RESideMenu', '~> 4.0.7'
#pod 'HHCategory', '~> 0.3.8'
pod 'HHUIViewExtension', '~> 1.0.0'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'

#pod 'QKChineseVerifyCode',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKVerifyCode'
#pod 'QKAFNetworkSDK',:svn=>'svn://wangxiaoli@192.168.1.193/apps/code/tags/Pods/QKAFNetworkSDK/1.0.0'
#pod 'LogManager',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/LogManager'
#pod 'FileManager',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/FileManager'
#pod 'QKGotoBaiduMap', :svn => 'svn://192.168.1.193/apps/code/trunk/Base/iOS/QKPublic/Helper/QKGotoBaiduMap'
#pod 'QKRecoderHelper',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKRecoderHelper'
#pod 'QKAlertView',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKAlertView'
#pod 'QKAliYunUpload',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKAliYunUpload'
#pod 'QKBaiduMapLocation',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKBaiduMapLocation'
#pod 'QKBLESDK',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKBLESDK'
#pod 'QKCompressImage',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKCompressImage'
#pod 'QKRecoderHelper',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKRecoderHelper'
#pod 'QKRecordInterfaceHelper',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKRecordInterfaceHelper'
#pod 'QKRSAHelper',:svn =>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/QKRSAHelper'
#pod 'Authentication',:svn=>'svn://wangxiaoli@192.168.1.193/apps/code/trunk/PublicManager/Public/Authentication'
#pod 'MBProgressHUD+DK', '~> 1.1.1'
#pod 'UIView+Helpers', '~> 1.4.0'
end
