platform:'ios','8.0'
target 'HuaHong' do
pod 'AFNetworking'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'BaiduMapKit'
pod 'SSZipArchive'
pod 'SSKeychain', '~> 1.4.1'
pod 'SDWebImage', '~> 4.2.3'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'iCarousel', '~> 1.8.3'
pod 'AVOSCloud'
pod 'FaceppSDK', '~> 2.0.0'
pod 'XYPieChart'
pod 'SystemServices', '~> 2.0.1'
pod 'HHCategory', '~> 0.3.8'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
end
