//
//  Public.h
//  HuaHong
//
//  Created by 华宏 on 2017/12/1.
//  Copyright © 2017年 huahong. All rights reserved.
//

#ifndef Public_h
#define Public_h

//#define kBaseURL @"http://192.168.0.5"
#define kBaseURL @"http://172.31.0.85"

#import <SVProgressHUD.h>
#import "BaseViewController.h"
#import "UIScrollView+Refresh.h"
#import "HuaHong-Bridging-Header.h"
#import "HuaHong-Swift.h"
//#import <SSZipArchive.h>
#import "ReactiveObjc.h"
#import <NSObject+RACKVOWrapper.h>
#import "BaseModel.h"
#import "AppDelegate.h"
#import "HUtils.h"
#import <Masonry.h>
#import "KVOController.h"
#import "CleanCacheHelp.h"
#import <SDWebImage/UIImageView+WebCache.h>
#import "HHRequestManager.h"

//#import "HHCategory.h"
#import "UIView+Extension.h"
#import "UIView+AutoLayout.h"
#import "UILabel+autoReSize.h"
#import "UIColor+Category.h"
#import "NSString+IdentityCard.h"
#import "NSArray+NSDictionary_Log.h"
#import "CALayer+borderColor.h"
#import "UIViewController+Alert.h"
#import "NSString+Hash.h"
#import "UIButton+space.h"
#import "NSArray+NSDirectory_Convert_m.h"
#import "UIImage+Category.h"
#import "NSDate+Category.h"
#import "UITextField+Limit.h"
#import "MBProgressHUD+add.h"
#import "NSDictionary+NilSafe.h"
#import "NSDictionary+Null.h"
#import "NSObject+add.h"
#import "YYCategories.h"
#import "UITextView+PlaceHolder.h"
#import "UIScrollView+EmptyDataSet.h"
#import "UICountingLabel.h"
#import "NSTimer+HHTimer.h"
//#import <FBShimmeringView.h>
//#import <AVOSCloud/AVOSCloud.h>

#import "Model.h"
#import "HHSwitch.h"

#import "MapViewController.h"
#import "WaterFallController.h"
#import "LightSinceController.h"
#import "ThreeDTouchController.h"
#import "VoiceController.h"
#import "TakePhotoController.h"
#import "ContactsController.h"
#import "CustomContactsController.h"
#import "RecorderViewController.h"
#import "ImagePickController.h"
#import "MovieFileOutputController.h"
#import "CustomVideoController.h"
#import "AnimationController.h"
#import "MultiRequestController.h"
#import "QRCodeController.h"
#import "CreatQRCodeController.h"
#import "LoadingViewController.h"
#import "AppendVideoController.h"
#import "TestViewController.h"
#import "TableViewVC.h"
#import "AnnotationController.h"
#import "SystemNavigationController.h"
#import "BaiDuMapController.h"
#import "DataStorageController.h"
#import "TouchController.h"
#import "ClockViewController.h"
#import "TimerController.h"
#import "TransitionController.h"
#import "DrawingBoardController.h"
#import "ThreadViewController.h"
#import "SessionRequestController.h"
#import "DownLoadViewController.h"
#import "SecurityController.h"
#import "RACViewController.h"
#import "BlockVC.h"
#import "FunctionViewController.h"
#import "ChainViewController.h"
#import "runtimeViewController.h"
#import "runloopViewController.h"
#import "BlueToothController.h"
#import "CBPeripheralViewController.h"
#import "LeanCloudViewController.h"
#import "FaceViewController.h"
#import "WebViewVC.h"
#import "TextViewVC.h"
#import "CoreDataController.h"
#import "ButtonVC.h"
#import "HttpsController.h"
#import "UpLoadViewController.h"
#import "DeleteFileController.h"
#import "XMLController.h"
#import "JSONPlistController.h"
#import "AFController.h"
#import "RegularExpressionController.h"
#import "BridgeController.h"
#import "StrategyController.h"
#import "HHSegmentController.h"
#import "HHFMDBController.h"
#import "HHLockController.h"
#import "HHPhotoBrowserController.h"
#import "HHCardController.h"
#import "MenuControllerVC.h"
#import "PageControlVC.h"
#import "WKWebViewVC.h"
#import "GravityViewController.h"
#import "CollisionViewController.h"
#import "SnapViewController.h"
#import "AttachmentBehaviorController.h"
#import "PushBehaviorController.h"
#import "CoreMotionController.h"
#import "PedometerViewController.h"
#import "MVVM_Controller.h"
#import "MVVMController.h"
#import "MVPController.h"
#import "KVOViewController.h"
#import "VideoRecordController.h"
#import "GPUImageController.h"
#import "HHAlertView.h"
#import "HHVideoPlayerController.h"
#import "BuryViewController.h"
#import "ContainerViewController.h"
#import "AdapterViewController.h"
#import "CaptureController.h"
#import "VideoEncodeDecodeController.h"


#endif /* Public_h */
